# Lab 9: Conditional Pipeline Execution
# Simple demo showing conditional execution based on file changes

stages:
  - test

variables:
  GIT_DEPTH: 50

# Java unit test pipeline - only runs when Calculator.java changes
java-test:
  stage: test
  image: openjdk:11-slim  
  script:
    - echo "=== Java Unit Test Pipeline ==="
    - java -version
    - echo "Compiling Calculator.java..."
    - javac Calculator.java
    - echo "Running Calculator..."
    - java Calculator
    - echo "✓ Java tests completed successfully"
  rules:
    - changes:
        - "Calculator.java"
      when: always
    - when: never

# Python unit test pipeline - only runs when calculator.py changes  
python-test:
  stage: test
  image: python:3.9-slim
  script:
    - echo "=== Python Unit Test Pipeline ==="
    - python --version
    - echo "Running calculator.py..."
    - python calculator.py
    - echo "✓ Python tests completed successfully"
  rules:
    - changes:
        - "calculator.py"
      when: always
    - when: never

# Manual job to test both (for demonstration)
test-both:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache openjdk11 python3
  script:
    - echo "=== Testing Both Applications ==="
    - echo "Compiling and running Java Calculator..."
    - javac Calculator.java && java Calculator
    - echo "Running Python calculator..."
    - python3 calculator.py
    - echo "✓ Both applications work correctly"
  rules:
    - when: manual
      allow_failure: true